/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test.project;

import java.sql.*;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author kalpa
 */
public class add_quote extends javax.swing.JFrame
{
    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;

    /**
     * Creates new form add_quote
     */
    public add_quote ()
    {
        initComponents();
        combobox();
        AutoCompleteDecorator.decorate(category_box);
    }
    private void combobox ()
    {
        try
          {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/quotes", "root", "2507");
            pstmt = conn.prepareStatement("SELECT DISTINCT quote_type FROM quotes");
            rs = pstmt.executeQuery();
            while(rs.next())
              {
                String name = rs.getString("quote_type");
                category_box.addItem(name);
              }
            //category_box.addItem("add new");
            category_box.setEditable(true);
            conn.close();
          }
        catch(ClassNotFoundException | SQLException e)
          {
            JOptionPane.showMessageDialog(null, e);
          }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        categoryLabel1 = new javax.swing.JLabel();
        quotelabel = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        another_button = new javax.swing.JButton();
        save_button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        quote_area = new javax.swing.JTextArea();
        menu_Button1 = new javax.swing.JButton();
        category_box = new javax.swing.JComboBox<>();
        EXIT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(5, 30, 30));

        categoryLabel1.setBackground(new java.awt.Color(0, 0, 51));
        categoryLabel1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        categoryLabel1.setForeground(new java.awt.Color(255, 204, 204));
        categoryLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        categoryLabel1.setText("CATEGORY:-");
        categoryLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        categoryLabel1.setOpaque(true);

        quotelabel.setBackground(new java.awt.Color(0, 0, 51));
        quotelabel.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        quotelabel.setForeground(new java.awt.Color(255, 204, 204));
        quotelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quotelabel.setText("QUOTE:-");
        quotelabel.setOpaque(true);

        header.setBackground(new java.awt.Color(51, 51, 51));
        header.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        header.setForeground(new java.awt.Color(255, 255, 204));
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("ADD QUOTE");
        header.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 255, 204), new java.awt.Color(0, 51, 51)));
        header.setOpaque(true);

        another_button.setBackground(new java.awt.Color(0, 0, 0));
        another_button.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 14)); // NOI18N
        another_button.setForeground(new java.awt.Color(204, 255, 204));
        another_button.setText("Add Another Quote");
        another_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        another_button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                another_buttonActionPerformed(evt);
            }
        });

        save_button.setBackground(new java.awt.Color(0, 0, 0));
        save_button.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 14)); // NOI18N
        save_button.setForeground(new java.awt.Color(204, 255, 204));
        save_button.setText("SAVE");
        save_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save_button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                save_buttonActionPerformed(evt);
            }
        });

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        quote_area.setBackground(new java.awt.Color(255, 255, 255));
        quote_area.setColumns(1);
        quote_area.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        quote_area.setForeground(new java.awt.Color(0, 0, 0));
        quote_area.setLineWrap(true);
        quote_area.setRows(1);
        quote_area.setWrapStyleWord(true);
        quote_area.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        quote_area.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        quote_area.setFocusCycleRoot(true);
        quote_area.setFocusTraversalPolicyProvider(true);
        quote_area.setFocusable(true);
        jScrollPane2.setViewportView(quote_area);

        menu_Button1.setBackground(new java.awt.Color(0, 0, 0));
        menu_Button1.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 14)); // NOI18N
        menu_Button1.setForeground(new java.awt.Color(204, 255, 204));
        menu_Button1.setText("MAIN MENU");
        menu_Button1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_Button1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                menu_Button1ActionPerformed(evt);
            }
        });

        category_box.setEditable(true);
        category_box.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        category_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select or type new...." }));
        category_box.setFocusCycleRoot(true);
        category_box.setNextFocusableComponent(quote_area);
        category_box.setRequestFocusEnabled(true);
        category_box.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                category_boxActionPerformed(evt);
            }
        });

        EXIT.setBackground(new java.awt.Color(0, 0, 0));
        EXIT.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 14)); // NOI18N
        EXIT.setForeground(new java.awt.Color(204, 255, 204));
        EXIT.setText("EXIT");
        EXIT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 204), null, null));
        EXIT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EXITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quotelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(category_box, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(save_button, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menu_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(another_button, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(categoryLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(category_box, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(quotelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(save_button, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu_Button1)
                    .addComponent(another_button)
                    .addComponent(EXIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        // TODO add your handling code here:
        try
          {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/quotes", "root", "2507");
            String sql = "insert into quotes(quote_type,quote) values(?,?)";
            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, (String) category_box.getSelectedItem());
            pstmt.setString(2, quote_area.getText());
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "successful");
            conn.close();

          }
        catch(Exception e)
          {
            JOptionPane.showMessageDialog(null, e);
          }

    }//GEN-LAST:event_save_buttonActionPerformed

    private void another_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_another_buttonActionPerformed
        // TODO add your handling code here:
        new add_quote().setVisible(true);
        dispose();
    }//GEN-LAST:event_another_buttonActionPerformed

    private void menu_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Button1ActionPerformed
        // TODO add your handling code here:
        new MAIN_FRAME().setVisible(true);
        dispose();
    }//GEN-LAST:event_menu_Button1ActionPerformed

    private void category_boxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_category_boxActionPerformed
    {//GEN-HEADEREND:event_category_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_category_boxActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EXITActionPerformed
    {//GEN-HEADEREND:event_EXITActionPerformed
        // TODO add your handling code here
        this.dispose();
    }//GEN-LAST:event_EXITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main (String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
          {
            for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
              {
                if("Nimbus".equals(info.getName()))
                  {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                  }
              }
          }
        catch(ClassNotFoundException ex)
          {
            java.util.logging.Logger.getLogger(add_quote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
        catch(InstantiationException ex)
          {
            java.util.logging.Logger.getLogger(add_quote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
        catch(IllegalAccessException ex)
          {
            java.util.logging.Logger.getLogger(add_quote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
        catch(javax.swing.UnsupportedLookAndFeelException ex)
          {
            java.util.logging.Logger.getLogger(add_quote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run ()
            {
                new add_quote().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT;
    private javax.swing.JButton another_button;
    private javax.swing.JLabel categoryLabel1;
    private javax.swing.JComboBox<String> category_box;
    private javax.swing.JLabel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton menu_Button1;
    private javax.swing.JTextArea quote_area;
    private javax.swing.JLabel quotelabel;
    private javax.swing.JButton save_button;
    // End of variables declaration//GEN-END:variables
}
