/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test.project;

import java.sql.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author kalpa
 */
public class categories extends javax.swing.JFrame
{
    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    /**
     * Creates new form categories
     */
    public categories ()
    {
        initComponents();
        c_list();
    }
    private void c_list ()
    {
        try
          {
            DefaultListModel DML = new DefaultListModel();
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/quotes", "root", "2507");
            pstmt = conn.prepareStatement("SELECT DISTINCT quote_type FROM quotes");
            rs = pstmt.executeQuery();
            while(rs.next())
              {
                String name = rs.getString("quote_type");
                DML.addElement(name);
              }
            category_list.setModel(DML);
            conn.close();
          }
        catch(ClassNotFoundException | SQLException e)
          {
            JOptionPane.showMessageDialog(null, e);
          }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        menu_Button1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        category_list = new javax.swing.JList<>();
        cat_label = new javax.swing.JLabel();
        EXIT = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        quote_area = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        title_area = new javax.swing.JTextArea();
        anotherquote_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(5, 30, 30));
        jPanel1.setForeground(new java.awt.Color(204, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(857, 416));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        menu_Button1.setBackground(new java.awt.Color(0, 0, 0));
        menu_Button1.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 14)); // NOI18N
        menu_Button1.setForeground(new java.awt.Color(204, 255, 204));
        menu_Button1.setText("MAIN MENU");
        menu_Button1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_Button1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                menu_Button1ActionPerformed(evt);
            }
        });

        category_list.setBackground(new java.awt.Color(204, 204, 255));
        category_list.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        category_list.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                category_listValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(category_list);

        cat_label.setBackground(new java.awt.Color(153, 204, 255));
        cat_label.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        cat_label.setForeground(new java.awt.Color(0, 0, 0));
        cat_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cat_label.setText("AVAILABLE CATEGORIES");
        cat_label.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cat_label.setOpaque(true);

        EXIT.setBackground(new java.awt.Color(0, 0, 0));
        EXIT.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 14)); // NOI18N
        EXIT.setForeground(new java.awt.Color(204, 255, 204));
        EXIT.setText("EXIT");
        EXIT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 204), null, null));
        EXIT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EXITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menu_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cat_label)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(cat_label, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu_Button1)
                    .addComponent(EXIT))
                .addContainerGap())
        );

        quote_area.setBackground(new java.awt.Color(255, 255, 204));
        quote_area.setColumns(20);
        quote_area.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        quote_area.setForeground(new java.awt.Color(0, 0, 0));
        quote_area.setLineWrap(true);
        quote_area.setRows(1);
        quote_area.setWrapStyleWord(true);
        quote_area.setAutoscrolls(false);
        quote_area.setMaximumSize(new java.awt.Dimension(233, 27));
        jScrollPane2.setViewportView(quote_area);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        title_area.setEditable(false);
        title_area.setBackground(new java.awt.Color(255, 255, 204));
        title_area.setColumns(20);
        title_area.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        title_area.setRows(1);
        title_area.setAutoscrolls(false);
        title_area.setMaximumSize(new java.awt.Dimension(14, 27));
        jScrollPane3.setViewportView(title_area);

        anotherquote_button.setBackground(new java.awt.Color(0, 0, 0));
        anotherquote_button.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 14)); // NOI18N
        anotherquote_button.setForeground(new java.awt.Color(204, 255, 204));
        anotherquote_button.setText("Show Another Quote");
        anotherquote_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 204), new java.awt.Color(0, 102, 102), null, new java.awt.Color(102, 255, 204)));
        anotherquote_button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                anotherquote_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(anotherquote_button, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(anotherquote_button)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Button1ActionPerformed
        // TODO add your handling code here:
        new MAIN_FRAME().setVisible(true);
        dispose();
    }//GEN-LAST:event_menu_Button1ActionPerformed

    private void category_listValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_category_listValueChanged
    {//GEN-HEADEREND:event_category_listValueChanged
        // TODO add your handling code here:
        String qt = (String) category_list.getSelectedValue();
        title_area.setText(qt);
        try
          {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/quotes", "root", "2507");
            pstmt = conn.prepareStatement("SELECT quote FROM quotes WHERE quote_type =? ORDER BY RAND() LIMIT 1");
            pstmt.setString(1, category_list.getSelectedValue());
            rs = pstmt.executeQuery();
            if(rs.next())
              {
                String quoteDesc = rs.getString("quote");

                quote_area.setText(quoteDesc);

              }
            else
              {
                quote_area.setText("");
              }
          }
        catch(ClassNotFoundException | SQLException e)
          {
            JOptionPane.showMessageDialog(null, e);
          }
    }//GEN-LAST:event_category_listValueChanged

    private void anotherquote_buttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_anotherquote_buttonActionPerformed
    {//GEN-HEADEREND:event_anotherquote_buttonActionPerformed
        // TODO add your handling code here:
        String qt = (String) category_list.getSelectedValue();
        title_area.setText(qt);
        try
          {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/quotes", "root", "2507");
            pstmt = conn.prepareStatement("SELECT quote FROM quotes WHERE quote_type =? ORDER BY RAND() LIMIT 1");
            pstmt.setString(1, category_list.getSelectedValue());
            rs = pstmt.executeQuery();
            if(rs.next())
              {
                String quoteDesc = rs.getString("quote");

                quote_area.setText(quoteDesc);

              }
            else
              {
                quote_area.setText("");
              }
          }
        catch(ClassNotFoundException | SQLException e)
          {
            JOptionPane.showMessageDialog(null, e);
          }

    }//GEN-LAST:event_anotherquote_buttonActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EXITActionPerformed
    {//GEN-HEADEREND:event_EXITActionPerformed
        // TODO add your handling code here
        this.dispose();
    }//GEN-LAST:event_EXITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main (String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
          {
            for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
              {
                if("Nimbus".equals(info.getName()))
                  {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                  }
              }
          }
        catch(ClassNotFoundException ex)
          {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
        catch(InstantiationException ex)
          {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
        catch(IllegalAccessException ex)
          {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
        catch(javax.swing.UnsupportedLookAndFeelException ex)
          {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run ()
            {
                new categories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT;
    private javax.swing.JButton anotherquote_button;
    private javax.swing.JLabel cat_label;
    private javax.swing.JList<String> category_list;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton menu_Button1;
    private javax.swing.JTextArea quote_area;
    private javax.swing.JTextArea title_area;
    // End of variables declaration//GEN-END:variables
}
